package gogreenserver.entity;

import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "insert_history_co2")
public class InsertHistoryCo2 {

    //auto generated by DB
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @Column(name = "insertid", nullable = false, updatable = false)
    private Long insertId;

    //Auto generated by DB
    @Column(name = "insert_date")
    private LocalDateTime insertDate;

    @Column(name = "username")
    private String userName;

    @Column(name = "activity_name")
    private String activityName;

    @Column(name = "activity_price", nullable = true)
    private Float activityPrice;

    @Column(name = "alternate_activity", nullable = true)
    private String alternateActivity;

    @Column(name = "alternate_activity_price", nullable = true)
    private Float alternateActivityPrice;

    @Column(name = "activity_is_localproduce", nullable = true)
    private Boolean activityIsLocalproduce;

    @Column(name = "alternate_activity_is_localproduce", nullable = true)
    private Boolean alternateActivityIsLocalproduce;

    @Column(name = "transport_distance_km", nullable = true)
    private Float transportDistanceKm;

    @Column(name = "energy_activity_duration_minutes", nullable = true)
    private Float energyActivityDurationMinutes;

    @Column(name = "energy_activity_temperature_area_m2", nullable = true)
    private Float energyActivityTempAreaM2;

    @Column(name = "energy_activity_temperature_degrees_decreased", nullable = true)
    private Float energyActivityTempDegreesDecreased;

    @Column(name = "co2_saved", nullable = true)
    private Float co2Saved;

    public Float getCo2Saved() {
        return co2Saved;
    }

    public void setCo2Saved(Float co2Saved) {
        this.co2Saved = co2Saved;
    }

    public LocalDateTime getInsertDate() {
        return insertDate;
    }


    public void setInsertDate(LocalDateTime insertDate) {
        this.insertDate = insertDate;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getActivityName() {
        return activityName;
    }

    public void setActivityName(String activityName) {
        this.activityName = activityName;
    }

    public Float getActivityPrice() {
        return activityPrice;
    }

    public void setActivityPrice(Float activityPrice) {
        this.activityPrice = activityPrice;
    }

    public String getAlternateActivity() {
        return alternateActivity;
    }

    public void setAlternateActivity(String alternateActivity) {
        this.alternateActivity = alternateActivity;
    }

    public Float getAlternateActivityPrice() {
        return alternateActivityPrice;
    }

    public void setAlternateActivityPrice(Float alternateActivityPrice) {
        this.alternateActivityPrice = alternateActivityPrice;
    }

    public Boolean getActivityIsLocalproduce() {
        return activityIsLocalproduce;
    }

    public void setActivityIsLocalproduce(Boolean activityIsLocalproduce) {
        this.activityIsLocalproduce = activityIsLocalproduce;
    }

    public Boolean getAlternateActivityIsLocalproduce() {
        return alternateActivityIsLocalproduce;
    }

    public void setAlternateActivityIsLocalproduce(Boolean alternateActivityIsLocalproduce) {
        this.alternateActivityIsLocalproduce = alternateActivityIsLocalproduce;
    }

    public Float getTransportDistanceKm() {
        return transportDistanceKm;
    }

    public void setTransportDistanceKm(Float transportDistanceKm) {
        this.transportDistanceKm = transportDistanceKm;
    }

    public Float getEnergyActivityDurationMinutes() {
        return energyActivityDurationMinutes;
    }

    public void setEnergyActivityDurationMinutes(Float energyActivityDurationMinutes) {
        this.energyActivityDurationMinutes = energyActivityDurationMinutes;
    }

    public Float getEnergyActivityTempAreaM2() {
        return energyActivityTempAreaM2;
    }

    public void setEnergyActivityTempAreaM2(Float energyActivityTempAreaM2) {
        this.energyActivityTempAreaM2 = energyActivityTempAreaM2;
    }

    public Float getEnergyActivityTempDegreesDecreased() {
        return energyActivityTempDegreesDecreased;
    }

    public void setEnergyActivityTempDegreesDecreased(Float energyActivityTempDegreesDecreased) {
        this.energyActivityTempDegreesDecreased = energyActivityTempDegreesDecreased;
    }


    // Define toString
    @Override
    public String toString() {
        return "InsertHistoryCo2{"
            + "insertId=" + insertId
            + ", insertDate=" + insertDate
            + ", userName='" + userName + '\''
            + ", activityName='" + activityName + '\''
            + ", activityPrice=" + activityPrice
            + ", alternateActivity='" + alternateActivity + '\''
            + ", alternateActivityPrice=" + alternateActivityPrice
            + ", activityIsLocalproduce=" + activityIsLocalproduce
            + ", alternateActivityIsLocalproduce=" + alternateActivityIsLocalproduce
            + ", transportDistanceKm=" + transportDistanceKm
            + ", energyActivityDurationMinutes=" + energyActivityDurationMinutes
            + ", energyActivityTempAreaM2=" + energyActivityTempAreaM2
            + ", energyActivityTempDegreesDecreased=" + energyActivityTempDegreesDecreased
            + ", co2Saved=" + co2Saved
            + '}';
    }
}
